### ISSUE TITLE
Implement bar chart

### ISSUE THREAD

**Issue by petcupaula** [RADAR-CNS/RADAR-Dashboard#105]
We'll probably need a bar chart component

**Comment by petcupaula** [comment]
Implemented bar chart that can handle both continuous and categorical data: [bar-chart-implementation](/RADAR-CNS/RADAR-Dashboard/tree/bar-chart-implementation)

Number of steps per hour or day is an example where we would have continuous data (time series), and number of answers for a specific question in a questionnaire is an example where we have categorical data. 

The bar chart with continuous data (time series) will not show a bar for time periods where there was no measurement (or the value was zero), which I think makes sense for counting the number of steps over time where we might have days with zero steps if for example the device is not worn. 

However, for the bar chart with time series to make sense, we need the time periods to be equivalent (like number of steps in either 1 day, or 1 hour, etc). I assume this will be handled in the backend?

Anything else that we need to consider for the first version of the bar chart?

@herkulano @kerzmaximilian

**Comment by herkulano** [comment]
Looks great! :shipit:

**Comment by herkulano** [comment]
@petcupaula Regarding the data, I agree completely. There should be no "holes" in the data. If for example, a day has no values, that day should be in the data with a value of zero.

**Comment by dennyverbeeck** [comment]
Great work! I also agree that all time points should be present on the graph. Perhaps it could be useful to make a visual distinction between 'zero' and 'no data'. For step counts these two will probably be equivalent. But let's say we're plotting a mood score, than a few days with a reported happiness of zero is very different than a few days of no data.

**Comment by herkulano** [comment]
@dennyverbeeck I agree. In that case, the data would still have that day (there would be no gaps in the data) but its value would be `null`.

**Comment by herkulano** [comment]
@dennyverbeeck Regarding the representation of the difference between `null` and `zero`, I think adding a visual representation for `zero` could add noise to the graph and make it more difficult to read, doing more harm that good. 

We should investigate further cases. But for example in regarding happiness it's common to have a scale from `1-10`, so there's always some form of representation in the chart when there's a value for that "day".

In the case of steps, food logging and others, it's common practice not to have this distinction between `zero` values and `null` values because of the noise it creates and it's assumption that it's impossible to have `zero` steps or food log, if you are using the device there will be at least a couple of steps.

**Comment by dennyverbeeck** [comment]
That's a good point about the scales. Just to be clear, i don't suggest to make a special treatment for `zero` itself. Just that the representation for `zero` and `null` not be identical. When you are looking at your own data you can make sense of the values. But here a clinician will be looking at the data as well. For instance, not wearing a device results in it reporting `zero` steps. Wearing a device but the battery died should result in no report at all, i.e. `null`. So was the patient not wearing the device? Is his motivation to participate in the trial declining? Did he simply forget to charge the device? I think a clinician might want to make the distinction. Of course i could be wrong about this :wink: 

However it's probably less straightforward then i initially thought. E.g. on a chart with 7 bars, looking at a week, it's easy to show a small grayed-out label 'No data' instead of a bar. When looking at a larger chunk of data this will indeed introduce unwanted noise and do more harm then good. So for now i just have a comment and no real suggestion yet :stuck_out_tongue:

**Comment by herkulano** [comment]
Agree, I'll try to sketch a couple of alternatives with subtlety in mind to make it easy to understand the difference but not get in the way of the overall readability of the chart.

**Comment by dennyverbeeck** [comment]
Perfect!

**Comment by herkulano** [comment]
Null values mockup:
![desktop 302-patient-empty](https://cloud.githubusercontent.com/assets/125300/23670553/bf91282a-0370-11e7-9d26-029ee37fb058.png)
