### ISSUE TITLE
Is there a color coordination in Multi-chart type?

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/RADAR-Dashboard#320]
I was wondering whether the same color represents the same data type in multi-charts. Clearly, If I have two acceleration data from two devices, are the x-axis data from both device represented by the same color? @mpgxvii 
![image](https://user-images.githubusercontent.com/1315378/43637030-00b9b492-9714-11e8-8c9e-9ce0d2b0f5d7.png)
This is a sample image. Do the same color represent same axis?

**Comment by mpgxvii** [comment]
Yes. The keys (in this case, x, y, and z) are taken from sourceData sensor keys (if it exists, they can be null for single line charts). If they have the same results (and same order) from the API then the colours should represent the same axis.

<img width="626" alt="screen shot 2018-08-03 at 13 21 34" src="https://user-images.githubusercontent.com/16977973/43642648-56626ea0-9720-11e8-81b3-0b1794b2d3f7.png">


I'm working on the labels next so that it becomes more clear.
